# We install python and packages by ourselves
language: minimal

notifications:
  email:
    recipients:  
      - xiao.hk1997@gmail.com
    on_success: always  
    on_failure: always

os:
  - osx

# Test notebooks in parallel
env:
  - NOTEBOOK=frequency_classifier.ipynb

before_install:
  # Install miniconda based on the OS
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O miniconda.sh
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    fi
  - bash miniconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate t-cell-image
  - conda list

script:
  # Need to run image_processing.ipynb to set up training images
  echo 'Hello world!'
